language: node_js
node_js: 
    - stable
deply:
  provider: heroku
  app: shareyourideas-nodejs
  api_key:
    secure: jIxJG3IDE8aCeXav4upN3qUQmTT+quqb2pxhKl7esLopofFZfVEzFdtHCjhq2asopxiTeoFqsNMNS80TLyKnU5YiJnDP1NSmb9grcGxfYcQo6+o1l2DI2LsYOiMXr0zLLrplsjMAUs4RzfY119tfAwtO4aicx4VhXYpw5qnv2LQJayD7JNnK95Q+NXRyabqAKGoVjpVbTf8etXT7N5AReiOcwXMl/S5xYmlpy2FYBtv4k7Y2Jq/mogaR386+jlPPfRT0C+unJbniY25Ky1RAjprnrth5NKwpyxy3MeCoUiTBGBAz46lezMfbe6tYHJtKFvdv/3LJaj2TxrFR+8TCO/fu3Fx7ZRHJZC0GbuLcu8MpINpbQt9ltKcagG5zrNsz5dmvOJmzlHREEMxNkyrX8M+JrZoombfWd8bH8WoruyWniocad64y+ttqs59Qmcmv4pxkGf4OLSznuZH2h0qUhujeZum62dAij3AQEiOGRsfNiPktKTPERDPwSrxazdl62ZjbNBADBOfCGjE8GjWRPNBWM4c54YiKZO+OnzXePfG+II6YIswNV8wEWILyb58f5pGUMryW3X4VgXM6TYnuF4ITC4ihU1gSlVl0gMZsarsodJ/A3oq+JjD0g+h3ZmV7XjwnddD/rzJ3jWOYrYSnN/CoiuQs+3NGjhF7M/N1IUA=
