version: "3"

services: 
    api:
      build:
        context: .
        dockerfile: DockerFile
      depends_on:
        - mongo
      environment:
        - PORT=5000
        - MONGO_URI=mongodb://mongo:27017/test
        - APPLICATION_NAME=Share your idea
        - JWT_SECRET=XBIDGSJFSLDKHCS€@IOAHDAHD
        - CACHE_KEY=mYsTRONGpASSWORD
        - SWAGGER_DOC=swaggerPROD
      ports:
        - "5000:5000"
    
    mongo:
      image: mongo  
    
